import type { Lesson, Question, SyllabusModule, Topic } from './types.js';

export const topics: Topic[] = [
  { id: 1, name: 'The Accounting Environment', paper: 'P1', studyWeight: 15 },
  { id: 2, name: 'Introduction to Bookkeeping', paper: 'P1', studyWeight: 25 },
  { id: 3, name: 'Introduction to Control Processes', paper: 'P1', studyWeight: 20 },
  { id: 4, name: 'The Preparation of Financial Statements', paper: 'P2', studyWeight: 30 },
  { id: 5, name: 'Accounting for End of Period Adjustments', paper: 'P2', studyWeight: 10 },
];

export const modules: SyllabusModule[] = [
  { id:'1.1',topicId:1,code:'1.1',name:'Business Organisations & Stakeholders',paper:'P1',studyWeight:4,focus:'Characteristics of organisations and how stakeholders use financial statements.',officialPoints:['Public sector organisations','Private sector organisations','Sole traders','Partnerships','Stakeholders and the business','Stakeholders’ use of financial statements'] },
  { id:'1.2',topicId:1,code:'1.2',name:'Accounting Concepts',paper:'P1',studyWeight:4,focus:'Understand the significance of the six concepts explicitly listed by Pearson.',officialPoints:['Consistency','Prudence','Accruals','Materiality','Money measurement','Business entity'] },
  { id:'1.3',topicId:1,code:'1.3',name:'Technology & Data Security',paper:'P1',studyWeight:4,focus:'Benefits of accounting technology and protection of accounting data.',officialPoints:['Accounting software','Spreadsheets','Data loss','Access','Confidentiality','Hardware protection','Software protection'] },
  { id:'1.4',topicId:1,code:'1.4',name:'Professional Ethics & Public Interest',paper:'P1',studyWeight:3,focus:'Ethical principles, their application and public interest.',officialPoints:['Principles of professional ethics','Application to accounting roles and functions','Public interest in accounting roles and functions'] },
  { id:'2.1',topicId:2,code:'2.1',name:'Business Documentation',paper:'P1',studyWeight:4,focus:'Purpose and preparation of common business documents.',officialPoints:['Purpose of business documents','Purchase order','Purchase invoice','Sales invoice','Credit note','Statement of account','Remittance advice','Petty cash voucher','Cash receipt'] },
  { id:'2.2',topicId:2,code:'2.2',name:'Books of Original Entry',paper:'P1',studyWeight:4,focus:'Purpose and preparation of books of original entry.',officialPoints:['Purpose of books of original entry','Purchases day book','Sales day book','Purchases returns book','Sales returns book','Three-column cash book','Petty cash book','Journal'],prerequisites:['2.1'] },
  { id:'2.3',topicId:2,code:'2.3',name:'Ledger Accounting & Double Entry',paper:'P1',studyWeight:5,focus:'Ledger purpose and double-entry recording.',officialPoints:['Purpose of nominal ledger','Purpose of receivables ledger','Purpose of payables ledger','Record transactions using double-entry principles'],prerequisites:['2.2'] },
  { id:'2.4',topicId:2,code:'2.4',name:'Capital vs Revenue Expenditure',paper:'P1',studyWeight:3,focus:'Distinguish expenditure types and explain why correct treatment matters.',officialPoints:['Capital expenditure','Revenue expenditure','Importance of correct treatment'] },
  { id:'2.5',topicId:2,code:'2.5',name:'Depreciation & Disposal',paper:'P1',studyWeight:4,focus:'Causes, methods, recording and disposal of non-current assets.',officialPoints:['Causes of depreciation','Straight line vs reducing balance','Calculate and record depreciation','Calculate and record profit or loss on disposal'],prerequisites:['2.3'] },
  { id:'2.6',topicId:2,code:'2.6',name:'Irrecoverable Debts',paper:'P1',studyWeight:3,focus:'Irrecoverable debts and provision for irrecoverable debts.',officialPoints:['Why provision is necessary','Distinguish debt from provision','Calculate and record debts and provision'],prerequisites:['2.3'] },
  { id:'2.7',topicId:2,code:'2.7',name:'Other Receivables & Payables',paper:'P1',studyWeight:2,focus:'Why, how and when to account for other receivables and payables.',officialPoints:['Why adjustments are necessary','Distinguish receivables from payables','Calculate and record them'],prerequisites:['2.3'] },
  { id:'3.1',topicId:3,code:'3.1',name:'Trial Balance',paper:'P1',studyWeight:4,focus:'Purpose, preparation and limitations of a trial balance.',officialPoints:['Purpose','Preparation','Limitations'],prerequisites:['2.3'] },
  { id:'3.2',topicId:3,code:'3.2',name:'Control Accounts',paper:'P1',studyWeight:5,focus:'Purpose and preparation of trade receivables/payables control accounts.',officialPoints:['Purpose of control accounts','Trade receivables control account','Trade payables control account'],prerequisites:['2.3'] },
  { id:'3.3',topicId:3,code:'3.3',name:'Errors, Journal Corrections & Suspense',paper:'P1',studyWeight:6,focus:'Identify, explain and correct errors, including use of suspense account.',officialPoints:['Errors that affect trial balance','Errors that do not affect trial balance','Journal corrections','Suspense account'],prerequisites:['2.3','3.1'] },
  { id:'3.4',topicId:3,code:'3.4',name:'Bank Reconciliation',paper:'P1',studyWeight:5,focus:'Purpose, process and preparation of bank reconciliation statements.',officialPoints:['Purpose','Process','Preparation of bank reconciliation statement'],prerequisites:['2.2','2.3'] },
  { id:'4.1',topicId:4,code:'4.1',name:'Sole Trader Financial Statements',paper:'P2',studyWeight:6,focus:'Prepare income statements and statements of financial position.',officialPoints:['Income statement: gross profit and profit for year','Statement of financial position: assets, liabilities and equity'],prerequisites:['2.3','2.4','2.5','2.6','2.7'] },
  { id:'4.2',topicId:4,code:'4.2',name:'Partnership Financial Statements',paper:'P2',studyWeight:8,focus:'Nature, rules and financial statements of partnerships.',officialPoints:['Nature and reasons for partnership','Nature and structure of LLP','Section 24 Partnership Act 1890: salaries, division of profit/loss, interest on loans, capital and drawings','Appropriation account','Income statement and appropriation account','Current and capital accounts','Statement of financial position with partners’ balances'],prerequisites:['4.1'] },
  { id:'4.3',topicId:4,code:'4.3',name:'Incomplete Records',paper:'P2',studyWeight:6,focus:'Reconstruct profit, revenue, purchases and financial statements from incomplete data.',officialPoints:['Profit from opening and closing equity','Revenue and purchases using accounting techniques including control accounts','Prepare financial statements from incomplete records'],prerequisites:['3.2','4.1'] },
  { id:'4.4',topicId:4,code:'4.4',name:'Accounting Ratios',paper:'P2',studyWeight:5,focus:'Calculate and interpret profitability and liquidity ratios.',officialPoints:['Profitability vs liquidity','Gross profit percentage','Profit for year as percentage of revenue','Return on capital employed','Current ratio','Liquid/acid test ratio'],prerequisites:['4.1'] },
  { id:'4.5',topicId:4,code:'4.5',name:'Manufacturing Accounts',paper:'P2',studyWeight:5,focus:'Inventory types and preparation of manufacturing accounts.',officialPoints:['Raw materials vs work-in-progress vs finished goods','Prime cost','Production cost','Total cost'],prerequisites:['4.1'] },
  { id:'5.1',topicId:5,code:'5.1',name:'Applying Accounting Concepts',paper:'P2',studyWeight:2,focus:'Apply the six official accounting concepts to end-of-period situations.',officialPoints:['Consistency','Prudence','Accruals','Materiality','Money measurement','Business entity'],prerequisites:['1.2'] },
  { id:'5.2',topicId:5,code:'5.2',name:'Depreciation & Disposal in Final Accounts',paper:'P2',studyWeight:3,focus:'Apply depreciation and disposal adjustments in financial statements.',officialPoints:['Causes','Straight line vs reducing balance','Calculate and record depreciation','Calculate and record disposal profit/loss'],prerequisites:['2.5','4.1'] },
  { id:'5.3',topicId:5,code:'5.3',name:'Irrecoverable Debt Adjustments',paper:'P2',studyWeight:3,focus:'Apply irrecoverable debt and provision adjustments in final accounts.',officialPoints:['Why provision is necessary','Distinguish debt and provision','Calculate and record both'],prerequisites:['2.6','4.1'] },
  { id:'5.4',topicId:5,code:'5.4',name:'Other Receivable & Payable Adjustments',paper:'P2',studyWeight:2,focus:'Apply other receivable/payable adjustments in final accounts.',officialPoints:['Why adjustments are necessary','Distinguish receivables and payables','Calculate and record both'],prerequisites:['2.7','4.1'] },
];


// Individual study checkpoints. These break each official module requirement into
// smaller tickable skills so partial learning can be tracked without falsely
// marking the whole module complete.
export const moduleChecklists: Record<string,string[]> = {
  '1.1':[
    'Understand public-sector organisations',
    'Understand private-sector organisations',
    'Understand the characteristics of sole traders',
    'Understand the characteristics of partnerships',
    'Identify different stakeholders of a business',
    'Explain how different stakeholders use financial statements',
  ],
  '1.2':[
    'Define and apply the consistency concept',
    'Define and apply the prudence concept',
    'Define and apply the accruals concept',
    'Define and apply the materiality concept',
    'Define and apply the money measurement concept',
    'Define and apply the business entity concept',
  ],
  '1.3':[
    'Explain benefits of accounting software',
    'Explain benefits of spreadsheets in accounting',
    'Understand the risk of data loss',
    'Understand risks from unauthorised access',
    'Understand confidentiality of accounting data',
    'Explain hardware methods used to protect accounting data',
    'Explain software methods used to protect accounting data',
  ],
  '1.4':[
    'Understand principles of professional ethics',
    'Apply ethical principles to accounting roles and functions',
    'Explain public interest in accounting roles and functions',
  ],
  '2.1':[
    'Explain the purpose of business documents',
    'Understand and prepare a purchase order',
    'Understand and prepare a purchase invoice',
    'Understand and prepare a sales invoice',
    'Understand and prepare a credit note',
    'Understand and prepare a statement of account',
    'Understand and prepare a remittance advice',
    'Understand and prepare a petty-cash voucher',
    'Understand and prepare a cash receipt',
  ],
  '2.2':[
    'Explain the purpose of books of original entry',
    'Prepare a purchases day book',
    'Prepare a sales day book',
    'Prepare a purchases returns book',
    'Prepare a sales returns book',
    'Prepare a three-column cash book',
    'Prepare a petty-cash book',
    'Prepare journal entries',
  ],
  '2.3':[
    'Explain the purpose of the nominal/general ledger',
    'Explain the purpose of the receivables ledger',
    'Explain the purpose of the payables ledger',
    'Understand debit and credit rules',
    'Record transactions using double-entry principles',
    'Balance ledger accounts',
  ],
  '2.4':[
    'Define and identify capital expenditure',
    'Define and identify revenue expenditure',
    'Classify expenditure correctly as capital or revenue',
    'Explain why correct capital/revenue treatment is important',
    'Explain the effect of incorrect classification on profit and financial position',
  ],
  '2.5':[
    'Explain causes of depreciation',
    'Calculate depreciation using the straight-line method',
    'Calculate depreciation using the reducing-balance method',
    'Compare straight-line and reducing-balance depreciation',
    'Record depreciation in the accounting records',
    'Calculate carrying value and profit/loss on disposal',
    'Record the disposal of a non-current asset',
  ],
  '2.6':[
    'Explain why a provision/allowance for irrecoverable debts is necessary',
    'Distinguish an irrecoverable debt from a provision/allowance',
    'Calculate an irrecoverable debt write-off',
    'Record an irrecoverable debt write-off',
    'Calculate a provision/allowance for irrecoverable debts',
    'Record changes in the provision/allowance',
  ],
  '2.7':[
    'Explain why other receivable/payable adjustments are necessary',
    'Distinguish other receivables from other payables',
    'Calculate other receivables/prepayments/accrued income',
    'Calculate other payables/accruals/income received in advance',
    'Record other receivable and payable adjustments',
  ],
  '3.1':[
    'Explain the purpose of a trial balance',
    'Prepare a trial balance',
    'Explain the limitations of a trial balance and errors it may not reveal',
  ],
  '3.2':[
    'Explain the purpose of control accounts',
    'Prepare a trade receivables control account',
    'Prepare a trade payables control account',
  ],
  '3.3':[
    'Identify and explain errors that affect trial-balance agreement',
    'Identify and explain errors that do not affect trial-balance agreement',
    'Recognise common error types such as omission, commission, principle, original entry, reversal and compensating errors',
    'Correct accounting errors using journal entries',
    'Explain the purpose of a suspense account',
    'Prepare and clear a suspense account',
  ],
  '3.4':[
    'Explain the purpose of a bank reconciliation',
    'Explain why cash-book and bank-statement balances may differ',
    'Update the cash book for bank-originated items',
    'Prepare a bank reconciliation statement',
  ],
  '4.1':[
    'Prepare the income statement and calculate gross profit',
    'Calculate profit for the year',
    'Prepare a statement of financial position with assets, liabilities and equity',
    'Apply relevant end-of-period adjustments when preparing sole-trader financial statements',
  ],
  '4.2':[
    'Understand the nature of a partnership and reasons for forming one',
    'Understand the nature and structure of a limited liability partnership (LLP)',
    'Understand relevant Section 24 Partnership Act 1890 provisions',
    'Account for partners’ salaries',
    'Account for the division of partnership profit or loss',
    'Account for interest on partners’ loans',
    'Understand partners’ capital and drawings',
    'Explain the purpose of an appropriation account',
    'Prepare a partnership income statement and appropriation account',
    'Prepare partners’ current accounts',
    'Prepare partners’ capital accounts',
    'Prepare a partnership statement of financial position showing partners’ balances',
  ],
  '4.3':[
    'Calculate profit using opening and closing equity/capital',
    'Calculate missing revenue/sales from incomplete records',
    'Calculate missing purchases from incomplete records',
    'Use control accounts and other accounting techniques to reconstruct missing figures',
    'Prepare an income statement from incomplete records',
    'Prepare a statement of financial position from incomplete records',
  ],
  '4.4':[
    'Distinguish profitability from liquidity',
    'Calculate and interpret gross profit percentage',
    'Calculate and interpret profit for the year as a percentage of revenue',
    'Calculate and interpret return on capital employed (ROCE)',
    'Calculate and interpret the current/working-capital ratio',
    'Calculate and interpret the liquid/acid-test ratio',
    'Compare ratios and explain possible reasons for changes',
  ],
  '4.5':[
    'Distinguish raw materials, work in progress and finished goods',
    'Calculate prime cost',
    'Calculate production cost',
    'Calculate total cost',
    'Prepare a manufacturing account',
  ],
  '5.1':[
    'Apply consistency to end-of-period accounting situations',
    'Apply prudence to end-of-period accounting situations',
    'Apply accruals to end-of-period accounting situations',
    'Apply materiality to end-of-period accounting situations',
    'Apply money measurement to end-of-period accounting situations',
    'Apply business entity to end-of-period accounting situations',
  ],
  '5.2':[
    'Explain causes of depreciation in financial-statement situations',
    'Choose/compare straight-line and reducing-balance methods',
    'Calculate depreciation for end-of-period adjustments',
    'Record depreciation in the income statement and statement of financial position',
    'Calculate and record profit/loss on disposal in final accounts',
  ],
  '5.3':[
    'Explain why a provision/allowance for irrecoverable debts is necessary',
    'Distinguish irrecoverable debts from the provision/allowance',
    'Write off and record irrecoverable debts in final accounts',
    'Calculate and record the provision/allowance adjustment',
    'Apply irrecoverable-debt adjustments to the income statement and statement of financial position',
  ],
  '5.4':[
    'Explain why other receivable/payable adjustments are necessary',
    'Distinguish other receivables from other payables',
    'Calculate and record other receivable adjustments',
    'Calculate and record other payable adjustments',
    'Apply these adjustments to the income statement and statement of financial position',
  ],
};

export const officialPaperInfo = {
  P1:{code:'4AC1/01',title:'Introduction to Bookkeeping and Accounting',marks:100,duration:'2 hours',date:'2026-10-28',scope:'Topics 1–3'},
  P2:{code:'4AC1/02',title:'Financial Statements',marks:50,duration:'1 hour 15 minutes',date:'2026-11-05',scope:'Topics 4–5; builds on Topics 1–3'},
};

export const questions: Question[] = [
  {id:'q-concept-1',moduleId:'1.2',type:'mcq',difficulty:'medium',paper:'P1',marks:1,tags:['concepts','prudence'],question:'Which accounting concept is most directly concerned with avoiding overstatement of assets and profit?',options:['Consistency','Prudence','Money measurement','Business entity'],answer:'Prudence',explanation:'Prudence requires caution so assets and profits are not overstated and liabilities/expenses are not understated.'},
  {id:'q-concept-2',moduleId:'1.2',type:'short',difficulty:'medium',paper:'P1',marks:2,tags:['concepts','business entity'],question:'Explain the business entity concept.',answer:'The business is treated as separate from its owner, so only business transactions are recorded in the business accounting records.',explanation:'A complete answer separates the business from the owner and links this to recording transactions.'},
  {id:'q-caprev-1',moduleId:'2.4',type:'mcq',difficulty:'medium',paper:'P1',marks:1,tags:['capital','revenue'],question:'A business pays to install a newly purchased machine. How should the installation cost normally be classified?',options:['Capital expenditure','Revenue expenditure','Revenue income','Capital income'],answer:'Capital expenditure',explanation:'A directly attributable cost of bringing a non-current asset into use forms part of the asset cost.'},
  {id:'q-caprev-2',moduleId:'2.4',type:'theory',difficulty:'hard',paper:'P1',marks:4,tags:['capital','revenue','error'],question:'Explain two effects of incorrectly treating capital expenditure as revenue expenditure.',answer:'Profit for the year will be understated because expenses are overstated; non-current assets and therefore equity/net assets will also be understated because the cost was not capitalised.',explanation:'Develop each effect: one on profit and one on the statement of financial position.'},
  {id:'q-dep-1',moduleId:'2.5',type:'calculation',difficulty:'easy',paper:'P1',marks:2,tags:['depreciation','straight-line'],question:'A machine cost $12,000 and has a residual value of $2,000. Its useful life is 5 years. Calculate annual straight-line depreciation.',answer:'$2,000 per year',explanation:'(12,000 − 2,000) ÷ 5 = 2,000.'},
  {id:'q-dep-2',moduleId:'2.5',type:'calculation',difficulty:'hard',paper:'P1',marks:3,tags:['depreciation','reducing-balance'],question:'Equipment has a carrying value of $8,000 at the start of the year. Depreciation is 20% reducing balance. Calculate depreciation and closing carrying value.',answer:'Depreciation $1,600; closing carrying value $6,400.',explanation:'8,000 × 20% = 1,600; 8,000 − 1,600 = 6,400.'},
  {id:'q-errors-1',moduleId:'3.3',type:'mcq',difficulty:'hard',paper:'P1',marks:1,tags:['errors','principle'],question:'A motor vehicle purchased for business use is debited to motor expenses. Which error is this?',options:['Omission','Commission','Principle','Original entry'],answer:'Principle',explanation:'The correct amount is entered on the correct side, but in the wrong class of account: expense instead of non-current asset.'},
  {id:'q-errors-2',moduleId:'3.3',type:'short',difficulty:'hard',paper:'P1',marks:3,tags:['suspense','errors'],question:'State why a suspense account may be opened and explain when it should close.',answer:'It is opened temporarily when the trial balance does not agree so the difference can be recorded while errors are investigated. It should close when all errors causing the difference have been corrected.',explanation:'The key ideas are temporary difference, investigation, and a nil balance after correction.'},
  {id:'q-bank-1',moduleId:'3.4',type:'mcq',difficulty:'medium',paper:'P1',marks:1,tags:['bank reconciliation'],question:'Which item normally appears on a bank reconciliation statement rather than requiring an entry in the updated cash book?',options:['Bank charge not yet recorded','Direct debit not yet recorded','Unpresented cheque','Standing order not yet recorded'],answer:'Unpresented cheque',explanation:'Items already in the cash book but not yet processed by the bank are reconciliation timing differences.'},
  {id:'q-bank-2',moduleId:'3.4',type:'calculation',difficulty:'hard',paper:'P1',marks:4,tags:['bank reconciliation'],question:'After updating the cash book, the bank balance is $4,600 debit. Cheques of $900 are unpresented and deposits of $1,200 are outstanding. Calculate the reconciled bank statement balance.',answer:'$4,300 debit',explanation:'Starting from the updated cash book debit balance: 4,600 + 900 − 1,200 = 4,300 debit, using the standard reconciliation direction.'},
  {id:'q-control-1',moduleId:'3.2',type:'theory',difficulty:'medium',paper:'P1',marks:4,tags:['control accounts'],question:'Explain two reasons why a business may maintain control accounts.',answer:'They provide an independent check on the totals in personal ledgers and help locate errors; they also provide quick total receivables/payables figures without adding every personal account.',explanation:'Each reason should be developed, not merely named.'},
  {id:'q-trial-1',moduleId:'3.1',type:'mcq',difficulty:'tricky',paper:'P1',marks:1,tags:['trial balance','errors'],question:'Which error will NOT cause the trial balance totals to disagree?',options:['Posting only the debit entry','Posting a debit as a credit','Complete reversal of entries','Incorrect addition of one ledger account'],answer:'Complete reversal of entries',explanation:'Both debit and credit are present for equal amounts, but on the wrong sides, so the trial balance can still agree.'},
  {id:'q-ratio-1',moduleId:'4.4',type:'calculation',difficulty:'medium',paper:'P2',marks:2,tags:['ratios','gross profit'],question:'Revenue is $80,000 and gross profit is $24,000. Calculate the gross profit percentage.',answer:'30%',explanation:'24,000 ÷ 80,000 × 100 = 30%.'},
  {id:'q-ratio-2',moduleId:'4.4',type:'theory',difficulty:'hard',paper:'P2',marks:4,tags:['ratios','interpretation'],question:'A business current ratio falls from 2.0:1 to 1.2:1. Explain what this may indicate.',answer:'Liquidity has weakened because current assets provide a smaller cover for current liabilities. However, the reason should be investigated because the change could come from efficient inventory reduction or from rising short-term debts.',explanation:'Strong ratio answers interpret the movement and avoid making an unsupported conclusion from one ratio alone.'},
  {id:'q-sole-1',moduleId:'4.1',type:'calculation',difficulty:'medium',paper:'P2',marks:3,tags:['financial statements'],question:'Revenue is $50,000, opening inventory $5,000, purchases $30,000 and closing inventory $7,000. Calculate cost of sales and gross profit.',answer:'Cost of sales $28,000; gross profit $22,000.',explanation:'Cost of sales = 5,000 + 30,000 − 7,000 = 28,000. Gross profit = 50,000 − 28,000 = 22,000.'},
  {id:'q-partner-1',moduleId:'4.2',type:'short',difficulty:'medium',paper:'P2',marks:2,tags:['partnership'],question:'State the purpose of a partnership appropriation account.',answer:'To show how the partnership profit or loss for the year is distributed between the partners according to the partnership agreement or applicable rules.',explanation:'It is an allocation statement, not a calculation of business operating profit.'},
  {id:'q-incomplete-1',moduleId:'4.3',type:'calculation',difficulty:'hard',paper:'P2',marks:3,tags:['incomplete records'],question:'Opening capital was $25,000 and closing capital $31,000. During the year the owner introduced $4,000 additional capital and withdrew $7,000. Calculate profit for the year.',answer:'$9,000',explanation:'Profit = closing capital − opening capital − additional capital + drawings = 31,000 − 25,000 − 4,000 + 7,000 = 9,000.'},
  {id:'q-manu-1',moduleId:'4.5',type:'mcq',difficulty:'medium',paper:'P2',marks:1,tags:['manufacturing'],question:'Which item is normally included in prime cost?',options:['Factory rent','Direct labour','Office salaries','Selling expenses'],answer:'Direct labour',explanation:'Prime cost consists of direct material, direct labour and other direct expenses.'},
  {id:'q-adj-1',moduleId:'5.4',type:'calculation',difficulty:'medium',paper:'P2',marks:2,tags:['accruals','adjustments'],question:'Insurance paid during the year was $2,400. At year end, $400 relates to the next accounting period. What insurance expense should be charged for the year?',answer:'$2,000',explanation:'The $400 prepayment is excluded from this year’s expense: 2,400 − 400 = 2,000.'},
  {id:'q-irr-1',moduleId:'5.3',type:'calculation',difficulty:'hard',paper:'P2',marks:3,tags:['irrecoverable debts','provision'],question:'Trade receivables after writing off irrecoverable debts are $20,000. A 5% provision is required. Calculate the closing provision.',answer:'$1,000',explanation:'20,000 × 5% = 1,000.'},
];

export const lessons: Record<string,Lesson> = {
  '1.2':{moduleId:'1.2',intro:'Accounting concepts are ideas that guide how transactions and financial information should be treated. Pearson explicitly lists six concepts for this specification.',keyTerms:[{term:'Consistency',definition:'Use the same accounting treatment from period to period unless a justified change is needed.'},{term:'Prudence',definition:'Use caution so assets and profit are not overstated and liabilities/expenses are not understated.'},{term:'Accruals',definition:'Record income and expenses in the accounting period to which they relate, not simply when cash moves.'},{term:'Materiality',definition:'Give proper attention to information significant enough to affect decisions.'},{term:'Money measurement',definition:'Record only items that can be expressed in monetary terms in the accounting records.'},{term:'Business entity',definition:'Treat the business as separate from its owner for accounting purposes.'}],rules:['Learn the exact six listed concepts.','In scenario questions, name the concept and explain the link to the facts.','Do not use a memorised definition without applying it when the question asks you to explain.'],examples:[{title:'Application example',body:'If the owner pays a personal electricity bill from the business bank account, the business entity concept requires the transaction to be treated as drawings rather than a business expense.'}],mistakes:['Naming a concept without explaining why it applies.','Confusing prudence with deliberately understating profit.','Treating cash timing as the same thing as the accruals concept.'],memoryTip:'C P A M M B — Consistency, Prudence, Accruals, Materiality, Money measurement, Business entity.',quickCheckQuestionIds:['q-concept-1','q-concept-2']},
  '2.4':{moduleId:'2.4',intro:'Capital expenditure creates or improves a non-current asset and benefits more than one accounting period. Revenue expenditure is incurred in the normal running or maintenance of the business and is charged as an expense.',keyTerms:[{term:'Capital expenditure',definition:'Expenditure on acquiring or improving a non-current asset.'},{term:'Revenue expenditure',definition:'Expenditure on day-to-day running, repairs and maintenance.'}],rules:['Acquisition + directly attributable costs needed to bring an asset into use are normally capital.','Routine repair and maintenance are revenue.','Misclassification affects both profit and the statement of financial position.'],examples:[{title:'Machine example',body:'Purchase price and installation of a new machine are capital expenditure. A later routine repair is revenue expenditure.'}],mistakes:['Assuming every large payment is capital.','Assuming every repair is capital.','Forgetting to explain the effect of misclassification on both profit and assets.'],memoryTip:'CAPITAL creates/improves CAPACITY; REVENUE keeps the business RUNNING.',quickCheckQuestionIds:['q-caprev-1','q-caprev-2']},
  '2.5':{moduleId:'2.5',intro:'Depreciation allocates the depreciable amount of a non-current asset over its useful life. This course requires straight-line and reducing-balance methods plus disposal calculations.',keyTerms:[{term:'Depreciation',definition:'The allocation of the cost of a non-current asset over its useful life.'},{term:'Carrying value',definition:'Cost less accumulated depreciation.'},{term:'Residual value',definition:'Expected value at the end of useful life.'}],rules:['Straight line: (cost − residual value) ÷ useful life, or a fixed percentage of original cost when instructed.','Reducing balance: fixed percentage × opening carrying value.','Profit/loss on disposal compares disposal proceeds with carrying value at disposal.'],examples:[{title:'Straight line example',body:'Cost $12,000, residual value $2,000, life 5 years → ($12,000 − $2,000) ÷ 5 = $2,000 per year.'},{title:'Disposal example',body:'If carrying value is $3,500 and proceeds are $4,000, profit on disposal is $500.'}],mistakes:['Using original cost each year for reducing balance.','Forgetting residual value when the straight-line formula requires it.','Comparing disposal proceeds with original cost instead of carrying value.'],memoryTip:'SL = SAME charge; RB = RATE × remaining BOOK value.',quickCheckQuestionIds:['q-dep-1','q-dep-2']},
  '3.2':{moduleId:'3.2',intro:'Control accounts summarise transactions recorded in personal ledgers. They help check accuracy and provide quick totals for receivables and payables.',keyTerms:[{term:'Trade receivables control account',definition:'Summary account for amounts owed by credit customers.'},{term:'Trade payables control account',definition:'Summary account for amounts owed to credit suppliers.'}],rules:['Receivables control broadly follows customer balances: credit sales increase receivables; receipts and returns inwards reduce them.','Payables control broadly follows supplier balances: credit purchases increase payables; payments and returns outwards reduce them.'],examples:[{title:'Why useful?',body:'If the control account total does not agree with the total of individual balances, the business knows an error exists and can narrow its search.'}],mistakes:['Putting cash sales into receivables control.','Confusing sales returns with purchases returns.','Giving only “find errors” without developing why that helps.'],memoryTip:'Receivables = customers owe US. Payables = WE owe suppliers.',quickCheckQuestionIds:['q-control-1']},
  '3.3':{moduleId:'3.3',intro:'Errors can either affect trial-balance agreement or leave it agreeing. You need to identify errors, correct them with journals, and use a suspense account where appropriate.',keyTerms:[{term:'Error of omission',definition:'A transaction is completely omitted from the books.'},{term:'Error of commission',definition:'Correct type of account, wrong individual account.'},{term:'Error of principle',definition:'Transaction entered in the wrong class/type of account.'},{term:'Error of original entry',definition:'Wrong amount entered in the original record and then posted consistently.'},{term:'Complete reversal',definition:'Correct accounts used but debit and credit entries are reversed.'},{term:'Compensating errors',definition:'Two or more errors cancel each other’s effect on the trial balance.'},{term:'Suspense account',definition:'Temporary account used for a trial-balance difference while errors are investigated.'}],rules:['Errors with equal debit and credit effects can leave the trial balance agreeing.','A one-sided error usually creates a trial-balance difference and may involve suspense.','Correct entries by asking: what was done, what should have been done, what adjustment bridges the difference?'],examples:[{title:'Principle example',body:'Buying a motor vehicle and debiting motor expenses uses the wrong class of account, so it is an error of principle.'}],mistakes:['Thinking every error causes a suspense account.','Correcting only one side when both accounts are wrong.','Memorising error names without recognising the pattern in a transaction.'],memoryTip:'O C P O R C — Omission, Commission, Principle, Original entry, Reversal, Compensating.',quickCheckQuestionIds:['q-errors-1','q-errors-2']},
  '3.4':{moduleId:'3.4',intro:'Bank reconciliation explains the difference between the updated cash-book bank balance and the bank-statement balance. First update the cash book for items the bank has recorded but the business has not, then reconcile timing differences.',keyTerms:[{term:'Unpresented cheque',definition:'Cheque recorded in the cash book but not yet presented to/processed by the bank.'},{term:'Outstanding deposit',definition:'Deposit recorded in the cash book but not yet credited by the bank.'},{term:'Updated cash book',definition:'Cash book after entering bank-originated items such as charges, direct debits or standing orders.'}],rules:['Step 1: update the cash book for missing bank-originated transactions.','Step 2: use the updated cash-book balance in the reconciliation.','Timing differences such as unpresented cheques normally remain on the reconciliation, not as new cash-book entries.'],examples:[{title:'Two-stage process',body:'If the bank statement shows a bank charge not in the cash book, update the cash book first. If a cheque is already in the cash book but not yet on the bank statement, leave the cash book alone and reconcile it.'}],mistakes:['Putting every difference into the cash book.','Reconciling before updating the cash book.','Mixing up outstanding deposits and unpresented cheques.'],memoryTip:'BANK-only item? Update BOOK. BOOK-already item waiting for bank? Reconcile.',quickCheckQuestionIds:['q-bank-1','q-bank-2']},
};
